### ISSUE TITLE
File `CONTRIBUTORS.md` missing

### ISSUE THREAD

**Issue by aksub99** [IMGIITRoorkee/omniport-docs#3]
This [section](https://github.com/IMGIITRoorkee/omniport-docs#contribution-guidelines) in `README.md` mentions a file called `CONTRIBUTORS.md` which does not seem to exist.

**Comment by shreyansh23** [comment]
This has been resolved with 9e86854. Thanks, @aksub99, for bringing this to our notice. You might want to resolve this issue in a similar way on our other repositories.
