### ISSUE TITLE
Add meta data:image

### ISSUE THREAD

**Issue by pradumangoyal** [IMGIITRoorkee/omniport-docs#4]
**Is your feature request related to a problem? Please describe.**
There is no metadata: image present of the hosted version of this documentation at ReadTheDocs.

![image](https://user-images.githubusercontent.com/34851451/58673476-22ca5180-8369-11e9-8eda-cf054ef2961b.png)
![image](https://user-images.githubusercontent.com/34851451/58673526-4d1c0f00-8369-11e9-998b-71d79b109452.png)

**Comment by dhruvkb** [comment]
I found a [resource](http://docutils.sourceforge.net/docs/ref/rst/directives.html#meta) that might help. @pradumangoyal please coordinate with @kunalsatpal and get some second-year designers on this. It's getting stale.

**Comment by dhruvkb** [comment]
This issue has been fixed by commit f6b1d37.

![image](https://user-images.githubusercontent.com/16580576/64485338-088ff180-d23d-11e9-9b2f-f29358749d74.png)
